version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "area/dependency"
    schedule:
      interval: "daily"
